### ISSUE TITLE
Page clock

### ISSUE THREAD

**Issue by Leoglme** [corentin35000/PiscineElixir-FrontEnd#16]
- [x] Afficher clock sur la home ( dashboard )  ?
- [x] Le user connecter peut signaler ses heures de départ et arrivé 
- [x] liste des "pointage" ?

**Comment by LaGeogeoTeam** [comment]
26/10/2023 14:42:11 - creation of the feature/16-Page-clock branch and branch link to issue 16 - LaGeogeoTeam

**Comment by Leoglme** [comment]
![Image](https://github.com/corentin35000/PiscineElixir-FrontEnd/assets/74193170/35f9a2f2-a7bc-4eb2-85c1-3812f3e91d94)



![Image](https://github.com/corentin35000/PiscineElixir-FrontEnd/assets/74193170/081664e7-0dc5-419c-b622-55c64ac50f52)

**Comment by Leoglme** [comment]
https://www.timizer.io/

**Comment by Leoglme** [comment]
![Image](https://github.com/corentin35000/PiscineElixir-FrontEnd/assets/74193170/94cd7448-2842-428a-a107-ad56123f8424)
